/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShopId = IDL.Nat;
export const ProductId = IDL.Nat;
export const Time = IDL.Int;
export const Shop = IDL.Record({
  'id' : ShopId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'isActive' : IDL.Bool,
  'isSuspended' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'shopId' : IDL.Opt(ShopId),
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'lowStockThreshold' : IDL.Nat,
  'shopId' : ShopId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ShopDashboard = IDL.Record({
  'totalProducts' : IDL.Nat,
  'outOfStockProducts' : IDL.Vec(Product),
  'outOfStockCount' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'lowStockProducts' : IDL.Vec(Product),
});
export const StockMovementId = IDL.Nat;
export const StockMovement = IDL.Record({
  'id' : StockMovementId,
  'shopId' : ShopId,
  'quantityChange' : IDL.Int,
  'productId' : ProductId,
  'timestamp' : Time,
});
export const StockStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'lowStock' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserToShop' : IDL.Func([IDL.Principal, IDL.Opt(ShopId)], [], []),
  'createAndAssignShop' : IDL.Func([IDL.Text], [ShopId], []),
  'createProduct' : IDL.Func(
      [ShopId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [ProductId],
      [],
    ),
  'createShop' : IDL.Func([IDL.Text, IDL.Principal], [ShopId], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
  'getOutOfStockProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getShop' : IDL.Func([ShopId], [Shop], ['query']),
  'getShopAnalytics' : IDL.Func([ShopId], [ShopDashboard], ['query']),
  'getShopProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
  'getShopStockMovements' : IDL.Func(
      [ShopId],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getStockMovements' : IDL.Func(
      [ProductId],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getStockStatus' : IDL.Func([ProductId], [StockStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reactivateShop' : IDL.Func([ShopId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'suspendShop' : IDL.Func([ShopId], [], []),
  'updateProduct' : IDL.Func([ProductId, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateStock' : IDL.Func([ProductId, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShopId = IDL.Nat;
  const ProductId = IDL.Nat;
  const Time = IDL.Int;
  const Shop = IDL.Record({
    'id' : ShopId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'isActive' : IDL.Bool,
    'isSuspended' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'shopId' : IDL.Opt(ShopId),
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'lowStockThreshold' : IDL.Nat,
    'shopId' : ShopId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ShopDashboard = IDL.Record({
    'totalProducts' : IDL.Nat,
    'outOfStockProducts' : IDL.Vec(Product),
    'outOfStockCount' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'lowStockProducts' : IDL.Vec(Product),
  });
  const StockMovementId = IDL.Nat;
  const StockMovement = IDL.Record({
    'id' : StockMovementId,
    'shopId' : ShopId,
    'quantityChange' : IDL.Int,
    'productId' : ProductId,
    'timestamp' : Time,
  });
  const StockStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'lowStock' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserToShop' : IDL.Func([IDL.Principal, IDL.Opt(ShopId)], [], []),
    'createAndAssignShop' : IDL.Func([IDL.Text], [ShopId], []),
    'createProduct' : IDL.Func(
        [ShopId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [ProductId],
        [],
      ),
    'createShop' : IDL.Func([IDL.Text, IDL.Principal], [ShopId], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllShops' : IDL.Func([], [IDL.Vec(Shop)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
    'getOutOfStockProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getShop' : IDL.Func([ShopId], [Shop], ['query']),
    'getShopAnalytics' : IDL.Func([ShopId], [ShopDashboard], ['query']),
    'getShopProducts' : IDL.Func([ShopId], [IDL.Vec(Product)], ['query']),
    'getShopStockMovements' : IDL.Func(
        [ShopId],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getStockMovements' : IDL.Func(
        [ProductId],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getStockStatus' : IDL.Func([ProductId], [StockStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reactivateShop' : IDL.Func([ShopId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'suspendShop' : IDL.Func([ShopId], [], []),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateStock' : IDL.Func([ProductId, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };