/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : ProductId,
  'lowStockThreshold' : bigint,
  'shopId' : ShopId,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
}
export type ProductId = bigint;
export interface Shop {
  'id' : ShopId,
  'owner' : Principal,
  'name' : string,
  'lastUpdated' : Time,
  'isActive' : boolean,
  'isSuspended' : boolean,
}
export interface ShopDashboard {
  'totalProducts' : bigint,
  'outOfStockProducts' : Array<Product>,
  'outOfStockCount' : bigint,
  'lowStockCount' : bigint,
  'lowStockProducts' : Array<Product>,
}
export type ShopId = bigint;
export interface StockMovement {
  'id' : StockMovementId,
  'shopId' : ShopId,
  'quantityChange' : bigint,
  'productId' : ProductId,
  'timestamp' : Time,
}
export type StockMovementId = bigint;
export type StockStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'lowStock' : bigint };
export type Time = bigint;
export interface UserProfile {
  'shopId' : [] | [ShopId],
  'name' : string,
  'isSuperAdmin' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserToShop' : ActorMethod<[Principal, [] | [ShopId]], undefined>,
  'createAndAssignShop' : ActorMethod<[string], ShopId>,
  'createProduct' : ActorMethod<
    [ShopId, string, string, bigint, bigint],
    ProductId
  >,
  'createShop' : ActorMethod<[string, Principal], ShopId>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllShops' : ActorMethod<[], Array<Shop>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLowStockProducts' : ActorMethod<[ShopId], Array<Product>>,
  'getOutOfStockProducts' : ActorMethod<[ShopId], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getShop' : ActorMethod<[ShopId], Shop>,
  'getShopAnalytics' : ActorMethod<[ShopId], ShopDashboard>,
  'getShopProducts' : ActorMethod<[ShopId], Array<Product>>,
  'getShopStockMovements' : ActorMethod<[ShopId], Array<StockMovement>>,
  'getStockMovements' : ActorMethod<[ProductId], Array<StockMovement>>,
  'getStockStatus' : ActorMethod<[ProductId], StockStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reactivateShop' : ActorMethod<[ShopId], undefined>,
  'resetSuperAdmin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'suspendShop' : ActorMethod<[ShopId], undefined>,
  'updateProduct' : ActorMethod<[ProductId, string, string, bigint], undefined>,
  'updateStock' : ActorMethod<[ProductId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];